mode: standalone
rootUser: "minio"
rootPassword: "minio123"

persistence:
  enabled: true
  size: 10Gi

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - host: minio.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    memory: 512Mi
    cpu: 250m

service:
  type: ClusterIP
