# helm/values.yaml
mode: standalone
rootUser: "minio"
rootPassword: "minio123"

persistence:
  enabled: true
  size: 1Gi

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - host: minio.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    memory: 256Mi
    cpu: 100m

replicas: 1

service:
  type: ClusterIP

console:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - minio-console.local